import React,{useEffect,useMemo,useRef,useState}from'react';import{Search,Send,MoreVertical,Plus,Heart,Settings,ArrowLeft,Copy,LogOut,UserPlus,Shield,Users,MessageCircle,Link as LinkIcon,X}from'lucide-react';import{supabase,supabaseConfigError}from'./supabase';import'./style.css';
const ADMIN_EMAIL='hoangthi3000@gmail.com';
const emptyMessages=[];
function App(){
 const[showLanding,setShowLanding]=useState(true),[session,setSession]=useState(null),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false),[profile,setProfile]=useState(null),[profileForm,setProfileForm]=useState({username:'',display_name:'',bio:''}),[profileError,setProfileError]=useState(''),[users,setUsers]=useState([]),[search,setSearch]=useState(''),[active,setActive]=useState(null),[messages,setMessages]=useState(emptyMessages),[text,setText]=useState(''),[loadingMessages,setLoadingMessages]=useState(false),[mobile,setMobile]=useState(false),[admin,setAdmin]=useState(false),[adminUsers,setAdminUsers]=useState([]),[adminChats,setAdminChats]=useState([]),[notice,setNotice]=useState('');
 const bottom=useRef(null);
 const isAdmin=session?.user?.email?.toLowerCase()===ADMIN_EMAIL;
 const publicPath=window.location.pathname.match(/^\/u\/([^/]+)\/?$/i);
 const publicUsername=publicPath?decodeURIComponent(publicPath[1]):'';
 useEffect(()=>{if(!supabase)return;let alive=true;(async()=>{const{data:{session:s}}=await supabase.auth.getSession();if(alive)setSession(s);const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>alive&&setSession(s));return()=>subscription.unsubscribe()})();return()=>{alive=false}},[]);
 useEffect(()=>{if(!supabase||!session){setProfile(null);setUsers([]);return}loadProfile()},[session]);
 useEffect(()=>{if(!supabase||!session||!profile)return;loadUsers()},[session,profile]);
 useEffect(()=>{if(!supabase||!publicUsername||!session) return;loadPublicUser(publicUsername)},[publicUsername,session]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages,active]);
 useEffect(()=>{if(!supabase||!session||!active)return;const timer=setInterval(()=>loadMessages(active.id,true),2500);return()=>clearInterval(timer)},[session,active]);
 async function loadProfile(){if(!supabase)return;const{data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle();if(error){setProfileError(error.message);return}if(data){setProfile(data);setProfileForm({username:data.username,display_name:data.display_name,bio:data.bio||''})}else setProfile(null)}
 async function loadUsers(){if(!supabase)return;const{data}=await supabase.from('profiles').select('id,username,display_name,avatar_url,bio').neq('id',session.user.id).order('display_name').limit(100);setUsers(data||[])}
 async function loadPublicUser(username){if(!supabase)return;const{data}=await supabase.from('profiles').select('id,username,display_name,avatar_url,bio').ilike('username',username).maybeSingle();if(data&&data.id!==session.user.id){openChat(data)}else if(data&&data.id===session.user.id)setNotice('This is your profile link. Share it with someone else.')}
 async function loadMessages(conversationId,silent=false){if(!supabase)return;if(!silent)setLoadingMessages(true);const{data,error}=await supabase.from('user_messages').select('id,sender_id,content,created_at').eq('conversation_id',conversationId).order('created_at',{ascending:true}).limit(500);if(!error)setMessages(data||[]);if(!silent)setLoadingMessages(false)}
 async function openChat(target){if(!supabase||!profile||target.id===profile.id)return;setActive(target);setMobile(true);setMessages([]);const low=[profile.id,target.id].sort();let{data:conversation}=await supabase.from('user_conversations').select('id').eq('user_one',low[0]).eq('user_two',low[1]).maybeSingle();if(!conversation){const r=await supabase.from('user_conversations').insert({user_one:low[0],user_two:low[1]}).select('id').single();conversation=r.data;if(r.error){setNotice(r.error.message);return}}setActive({...target,conversation_id:conversation.id});await loadMessages(conversation.id)}
 async function send(){if(!supabase)return;const value=text.trim();if(!value||!active||!active.conversation_id)return;setText('');const{data,error}=await supabase.from('user_messages').insert({conversation_id:active.conversation_id,sender_id:profile.id,content:value}).select('id,sender_id,content,created_at').single();if(error){setNotice(error.message);setText(value);return}setMessages(m=>[...m,data]);await supabase.from('user_conversations').update({updated_at:new Date().toISOString()}).eq('id',active.conversation_id)}
 async function authSubmit(e){e.preventDefault();if(!supabase){setAuthError(supabaseConfigError||'Supabase is not configured.');return}setAuthError('');setAuthBusy(true);try{if(authMode==='signup'){const r=await supabase.auth.signUp({email:email.trim(),password});if(r.error)throw r.error;if(!r.data.session){setAuthError('Check your email to confirm your account, then sign in.')}else{setNotice('Account created.');setEmail('');setPassword('')}}else{const r=await supabase.auth.signInWithPassword({email:email.trim(),password});if(r.error)throw r.error}}catch(err){setAuthError(err.message||'Unable to continue.')}finally{setAuthBusy(false)}}
 async function saveProfile(e){e.preventDefault();if(!supabase)return;setProfileError('');const username=profileForm.username.trim().toLowerCase();const display_name=profileForm.display_name.trim();if(!/^[a-z0-9_]{3,30}$/.test(username)){setProfileError('Username must be 3–30 characters using letters, numbers, or _.');return}if(!display_name){setProfileError('Enter a display name.');return}const payload={id:session.user.id,username,display_name,bio:profileForm.bio.trim()||null,updated_at:new Date().toISOString()};const{data,error}=await supabase.from('profiles').upsert(payload).select('*').single();if(error){setProfileError(error.message);return}setProfile(data);setNotice('Profile saved.');loadUsers()}
 async function signOut(){if(supabase)await supabase.auth.signOut();setActive(null);setMessages([]);setAdmin(false)}
 async function copyLink(){const link=`${window.location.origin}/u/${profile.username}`;await navigator.clipboard?.writeText(link);setNotice('Your profile link was copied.');}
 async function openAdmin(){if(!supabase)return;setAdmin(true);setMobile(false);const u=await supabase.from('profiles').select('id,username,display_name,bio,created_at').order('created_at',{ascending:false});setAdminUsers(u.data||[]);const c=await supabase.from('user_conversations').select('id,user_one,user_two,created_at,updated_at').order('updated_at',{ascending:false}).limit(200);setAdminChats(c.data||[])}
 const filtered=useMemo(()=>users.filter(u=>(u.display_name+' '+u.username).toLowerCase().includes(search.toLowerCase())),[users,search]);
 if(showLanding)return <Landing onStart={()=>setShowLanding(false)}/>;
 if(!supabase)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} error={supabaseConfigError} busy={false} onSubmit={authSubmit}/>;
 if(!session)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} error={authError} busy={authBusy} onSubmit={authSubmit}/>;
 if(!profile)return <ProfileSetup form={profileForm} setForm={setProfileForm} error={profileError} onSubmit={saveProfile} email={session.user.email}/>;
 if(admin&&isAdmin)return <AdminView users={adminUsers} chats={adminChats} onBack={()=>setAdmin(false)} onSignOut={signOut}/>;
 return <main className={mobile?'mobile-chat':''}>
  <aside><header><div className="brand"><b>Zap</b><span>Connect and chat</span></div><button className="icon" onClick={()=>setNotice('Settings are available from your profile menu.')}><MoreVertical/></button></header>
   <div className="my-profile"><div className="avatar">{profile.display_name[0].toUpperCase()}</div><div className="my-meta"><strong>{profile.display_name}</strong><small>@{profile.username}</small></div><button className="icon" onClick={copyLink} title="Copy profile link"><LinkIcon size={18}/></button></div>
   <div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find someone"/></div>
   <div className="section-title"><span>People</span><button onClick={copyLink}><Copy size={15}/> My link</button></div>
   <div className="chatlist">{filtered.map(u=><button key={u.id} className={'chat '+(active?.id===u.id?'selected':'')} onClick={()=>openChat(u)}><div className="avatar">{u.display_name[0].toUpperCase()}</div><div className="meta"><strong>{u.display_name}</strong><small>@{u.username}</small></div></button>)}{!filtered.length&&<div className="empty">No one found yet.</div>}</div>
   <div className="sidebottom"><button onClick={copyLink}><LinkIcon/> Share my profile</button>{isAdmin&&<button onClick={openAdmin}><Shield/> Admin</button>}<button onClick={signOut}><LogOut/> Sign out</button></div>
  </aside>
  <section><header className="top">{active?<><button className="back icon" onClick={()=>setMobile(false)}><ArrowLeft/></button><div className="avatar">{active.display_name[0].toUpperCase()}</div><div><strong>{active.display_name}</strong><small>@{active.username}</small></div><div className="actions"><button className="icon" onClick={()=>setNotice('This chat is private.')}><MoreVertical/></button></div></>:<div className="welcome"><MessageCircle/><div><strong>Start a conversation</strong><small>Find someone and send a message.</small></div></div>}</header>
   {active?<><div className="messages">{loadingMessages&&!messages.length?<div className="empty">Loading messages…</div>:messages.map(m=><div key={m.id} className={'bubble '+(m.sender_id===profile.id?'mine':'')}><span>{m.content}</span>{m.sender_id===profile.id&&<small>✓✓</small>}</div>)}<div ref={bottom}/></div><div className="composer"><button className="icon"><Plus/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&send()} placeholder="Write a message"/><button className="send" onClick={send}><Send size={18}/></button></div></>:<div className="empty-panel"><Users/><h2>Find someone to chat with</h2><p>Search by username or display name, or share your profile link so someone can find you.</p><button onClick={copyLink}><Copy size={17}/> Copy my link</button></div>}
  </section>
  {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}<X size={15}/></div>}
 </main>;
}
function Landing({onStart}){return <main className="landing"><div className="landing-shell"><div className="landing-top"><div className="landing-logo"><span>⚡</span> Zap</div><button className="landing-menu"><MoreVertical size={21}/></button></div><div className="landing-copy"><div className="phone-preview"><div className="phone-status"><span>9:41</span><span>● ● ◔</span></div><div className="phone-head"><div><b>Zap</b><small>Connect. Talk. Stay close.</small></div><Search size={22}/></div><div className="phone-search"><Search size={18}/><span>Search people or messages</span></div><div className="preview-cards"><div><Users size={21}/><span>Find someone</span></div><div><LinkIcon size={21}/><span>Share your link</span></div></div><div className="preview-title">Chats</div><div className="preview-chat"><i>🙂</i><div><b>Start a conversation</b><small>Connect with people you know</small></div></div><div className="preview-chat"><i>💬</i><div><b>Private messaging</b><small>Simple, fast and personal</small></div></div><div className="preview-nav"><span>●<small>Chats</small></span><span>◌<small>People</small></span><span>◉<small>Profile</small></span></div></div><div className="landing-text"><span className="eyebrow">PRIVATE • SIMPLE • PERSONAL</span><h1>Connect with the people who matter.</h1><p>Find someone, share your personal link, and start a private conversation in a clean mobile-style experience.</p><button className="landing-start" onClick={onStart}>Get started <ArrowLeft size={19}/></button><small className="landing-note">Already have an account? Sign in after getting started.</small></div></div></div></main>}
function Auth({mode,setMode,email,setEmail,password,setPassword,error,busy,onSubmit}){return <main className="auth-screen"><div className="auth-card"><div className="auth-logo">Zap</div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>{mode==='login'?'Sign in to find people and chat.':'Register to create your profile and share your link.'}</p><form onSubmit={onSubmit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required autoComplete={mode==='login'?'current-password':'new-password'}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Register'}</button></form><button className="switch" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?"Don't have an account? Register":"Already registered? Sign in"}</button></div></main>}
function ProfileSetup({form,setForm,error,onSubmit,email}){return <main className="auth-screen"><div className="auth-card"><div className="auth-logo">Zap</div><h1>Create your profile</h1><p>Choose what other registered users will see.</p><form onSubmit={onSubmit}><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="yourname" required/></label><label>Display name<input value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} placeholder="Your name" required/></label><label>About you<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} maxLength={280} placeholder="A short introduction (optional)"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary">Continue</button></form><small className="account-note">Signed in as {email}</small></div></main>}
function AdminView({users,chats,onBack,onSignOut}){return <main className="admin-screen"><header className="admin-header"><button className="icon" onClick={onBack}><ArrowLeft/></button><div><strong>Admin</strong><small>Account management</small></div><button className="logout" onClick={onSignOut}><LogOut size={17}/> Sign out</button></header><div className="admin-grid"><section className="admin-card"><div className="admin-title"><Users/><div><strong>Users</strong><small>{users.length} registered</small></div></div><div className="admin-list">{users.map(u=><div className="admin-row" key={u.id}><div className="avatar">{u.display_name[0].toUpperCase()}</div><div><strong>{u.display_name}</strong><small>@{u.username}</small></div></div>)}</div></section><section className="admin-card"><div className="admin-title"><MessageCircle/><div><strong>Conversations</strong><small>{chats.length} conversations</small></div></div><div className="admin-list">{chats.map(c=><div className="admin-row" key={c.id}><div className="avatar">C</div><div><strong>Private conversation</strong><small>{new Date(c.updated_at||c.created_at).toLocaleString()}</small></div></div>)}</div></section></div></main>}
export default App;